tap "browsh-org/browsh"
tap "buo/cask-upgrade"
tap "github/gh"
tap "koekeishiya/formulae"
tap "sst/tap"
tap "timescale/tap"
brew "aalib"
brew "ack"
brew "ansifilter"
brew "xz"
brew "jpeg-xl"
brew "aom"
brew "gettext"
brew "aria2"
brew "automake"
brew "awslogs"
brew "bash"
brew "boxes"
brew "cabextract"
brew "glib"
brew "cdrtools"
brew "cmake"
brew "cookiecutter"
brew "coreutils"
brew "cowsay"
brew "ctags"
brew "curl"
brew "diff-so-fancy"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "erlang"
brew "fd"
brew "libidn2"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libass"
brew "libmicrohttpd"
brew "librist"
brew "pango"
brew "srt"
brew "tesseract"
brew "ffmpeg"
brew "flyway"
brew "python@3.12"
brew "fontforge"
brew "fortune"
brew "fzf"
brew "gcc"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "libassuan"
brew "gnupg"
brew "gobject-introspection"
brew "gradle"
brew "grafana"
brew "node"
brew "grunt-cli"
brew "guile"
brew "httpie"
brew "hub"
brew "hyperfine"
brew "libheif"
brew "imagemagick"
brew "jmeter"
brew "jq"
brew "just"
brew "lazygit"
brew "leveldb"
brew "libfido2"
brew "libwebsockets"
brew "llvm"
brew "lolcat"
brew "lua-language-server"
brew "luarocks"
brew "lynx"
brew "markdownlint-cli"
brew "mas"
brew "mercurial"
brew "mkcert"
brew "mosquitto"
brew "mycli"
brew "mysql", restart_service: :changed
brew "mysql-client"
brew "neovim"
brew "nghttp2"
brew "ninja"
brew "nmap"
brew "nss"
brew "nvm"
brew "pandoc"
brew "perl"
brew "pgcli"
brew "php"
brew "pipenv"
brew "postgresql@14"
brew "postgresql@15"
brew "postgresql@16"
brew "pv"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.10"
brew "python@3.11"
brew "python@3.9"
brew "qemu"
brew "rabbitmq"
brew "ranger"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "rlwrap"
brew "rust"
brew "shellcheck"
brew "starship"
brew "superfile"
brew "telnet"
brew "tmux"
brew "tree"
brew "typescript-language-server"
brew "vim"
brew "w3m"
brew "wget"
brew "wimlib"
brew "wp-cli"
brew "yarn"
brew "sst/tap/opencode"
cask "alacritty"
cask "emacs-app"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "rectangle"
cask "warp"
mas "1Password for Safari", id: 1569813296
mas "Bear", id: 1091189122
mas "Codye", id: 1516894961
mas "Data Jar", id: 1453273600
mas "Developer", id: 640199958
mas "Fantastical", id: 975937182
mas "Instapaper Save", id: 1481302432
mas "Jayson", id: 1468691718
mas "Jolt of Caffeine", id: 1437130425
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "MKPlayer", id: 1335612105
mas "Notion Web Clipper", id: 1559269364
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "Pages", id: 409201541
mas "Private LLM", id: 6448106860
mas "Prompt", id: 1594420480
mas "Reeder", id: 1529448980
mas "Sequel Ace", id: 1518036000
mas "Slack", id: 803453959
mas "TestFlight", id: 899247664
mas "Toggl Track", id: 957734279
mas "ToothFairy", id: 1191449274
mas "Xcode", id: 497799835
